<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>CafRead -- Online Reading</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="CafRead.com">

		<link href="/assets/bootstrap/css/bootstrap.css" rel="stylesheet">
		<link href="/assets/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
		
		<link href="/assets/css/template.css" rel="stylesheet">
		<link href="/assets/css/style2.css" rel="stylesheet">
		
		<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
		<script src="assets/bootstrap/js/html5shiv.js"></script>
		<![endif]-->

		<!-- Fav and touch icons -->
		<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144x144-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apple-touch-icon-114x114-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apple-touch-icon-72x72-precomposed.png">
		<link rel="apple-touch-icon-precomposed" href="/apple-touch-icon-57x57-precomposed.png">
		<link rel="shortcut icon" href="/favicon.ico">
	</head>

	<body class="bg-color-white">
