<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Log out -- CafRead</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="English Online Reading">
		<meta name="author" content="cafread.com">

		<link href="/assets/css/style3.css" rel="stylesheet">
		<style type="text/css">

		div.page,
		div.page-footer
		{
			margin: 0 auto 2px;
			width: 30%;
			padding-top: 100px;
			padding-bottom:100px;
		}

		</style>



		<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
		<script src="/assets/bootstrap/js/html5shiv.js"></script>
		<![endif]-->

		<!-- Fav and touch icons -->
		<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144x144-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apple-touch-icon-114x114-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apple-touch-icon-72x72-precomposed.png">
		<link rel="apple-touch-icon-precomposed" href="/apple-touch-icon-57x57-precomposed.png">
		<link rel="shortcut icon" href="/favicon.ico">

	</head>

	<body>
		<div class="page">
			<?php echo $this->content; ?>
		</div>

		<script src="/assets/js/jquery-1.10.1.min.js"></script>
		
		<div class="page-footer" style="clear: both;">
			<footer>
				<p>
					&copy; <a href="/">CafRead.com</a> 2013
				</p>
			</footer>
		</div>
	</body>
</html>
